/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author elie
 */
public class CareerRolePage extends javax.swing.JPanel {

    /**
     * Creates new form CareerRolePage
     */
    public CareerRolePage() {
        initComponents();
         loadSubjects();
        loadCareerRoles();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roleIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roleNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        minScoreTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        requiredSubjectsCombo = new javax.swing.JComboBox<>();
        descriptionTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel1.add(rightPanel, java.awt.BorderLayout.LINE_END);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 381));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Career Role Form");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role ID");

        roleIdTxt.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");

        addBtn.setBackground(new java.awt.Color(0, 0, 51));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(0, 51, 51));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Required min score");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Required Subjects");

        requiredSubjectsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requiredSubjectsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roleNameTxt)
                            .addComponent(roleIdTxt)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(72, 72, 72)
                            .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(24, 24, 24)
                            .addComponent(minScoreTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(addBtn)
                            .addGap(18, 18, 18)
                            .addComponent(updateBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deleteBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(refreshBtn))))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requiredSubjectsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(minScoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addGap(26, 26, 26))
        );

        mainPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lists of Career Roles");

        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Role ID", "Role Name", "Description", "Required Subjects", "Required min score"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(searchTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
                                       
    try {
        String roleName = roleNameTxt.getText().trim();
        String description = descriptionTxt.getText().trim();
        String minScoreStr = minScoreTxt.getText().trim();
        String selectedSubject = (String) requiredSubjectsCombo.getSelectedItem();

        // --- VALIDATE ROLE NAME ---
        if (roleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Role Name cannot be empty.");
            return;
        }

        // --- VALIDATE DESCRIPTION ---
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty.");
            return;
        }

        // --- VALIDATE MIN SCORE ---
        if (minScoreStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Minimum score cannot be empty.");
            return;
        }

        int minScore;
        try {
            minScore = Integer.parseInt(minScoreStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Minimum score must be a valid number.");
            return;
        }

        if (minScore < 60) {
            JOptionPane.showMessageDialog(this, "Minimum score for all careers must be at least 60.");
            return;
        }

        // --- VALIDATE SUBJECT SELECTION ---
        if (selectedSubject == null || selectedSubject.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a required subject.");
            return;
        }

        int subjectId = Integer.parseInt(selectedSubject.split(" - ")[0]);

        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");

        // --- CHECK ROLE NAME EXISTS ---
        PreparedStatement checkName = con.prepareStatement(
            "SELECT * FROM career_role WHERE role_name=?");
        checkName.setString(1, roleName);
        ResultSet rsName = checkName.executeQuery();
        if (rsName.next()) {
            JOptionPane.showMessageDialog(this, "Role Name already exists!");
            rsName.close();
            checkName.close();
            con.close();
            return;
        }
        rsName.close();
        checkName.close();

        // --- CHECK SAME SUBJECT + MIN SCORE COMBINATION ---
        PreparedStatement checkCombo = con.prepareStatement(
            "SELECT * FROM career_role WHERE role_name=? AND required_subject_id=? AND required_min_score=?");
        checkCombo.setString(1, roleName);
        checkCombo.setInt(2, subjectId);
        checkCombo.setInt(3, minScore);
        ResultSet rsCombo = checkCombo.executeQuery();
        if (rsCombo.next()) {
            JOptionPane.showMessageDialog(this, "This career with the same subject and minimum score already exists!");
            rsCombo.close();
            checkCombo.close();
            con.close();
            return;
        }
        rsCombo.close();
        checkCombo.close();

        // --- INSERT INTO DATABASE ---
        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO career_role(role_name, description, required_subject_id, required_min_score) VALUES(?,?,?,?)");
        ps.setString(1, roleName);
        ps.setString(2, description);
        ps.setInt(3, subjectId);
        ps.setInt(4, minScore);

        int inserted = ps.executeUpdate();
        if (inserted > 0) {
            JOptionPane.showMessageDialog(this, "Career role added successfully!");
            clearForm();
            loadCareerRoles();
        }

        ps.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding career role: " + e.getMessage());
    }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
                                                                                     
    try {
        if (roleIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search or select a career role first.");
            return;
        }

        String roleName = roleNameTxt.getText().trim();
        String description = descriptionTxt.getText().trim();
        String minScoreStr = minScoreTxt.getText().trim();
        String selectedSubject = (String) requiredSubjectsCombo.getSelectedItem();
        int roleId = Integer.parseInt(roleIdTxt.getText().trim());

        // --- VALIDATE ROLE NAME ---
        if (roleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Role Name cannot be empty.");
            return;
        }

        // --- VALIDATE DESCRIPTION ---
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty.");
            return;
        }

        // --- VALIDATE MIN SCORE ---
        if (minScoreStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Minimum score cannot be empty.");
            return;
        }

        int minScore;
        try {
            minScore = Integer.parseInt(minScoreStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Minimum score must be a valid number.");
            return;
        }

        if (minScore < 60) {
            JOptionPane.showMessageDialog(this, "Minimum score for all careers must be at least 60.");
            return;
        }

        // --- VALIDATE SUBJECT SELECTION ---
        if (selectedSubject == null || selectedSubject.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a required subject.");
            return;
        }

        int subjectId = Integer.parseInt(selectedSubject.split(" - ")[0]);

        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");

        // --- CHECK ROLE NAME EXISTS FOR OTHER RECORDS ---
        PreparedStatement checkName = con.prepareStatement(
            "SELECT * FROM career_role WHERE role_name=? AND role_id<>?");
        checkName.setString(1, roleName);
        checkName.setInt(2, roleId);
        ResultSet rsName = checkName.executeQuery();
        if (rsName.next()) {
            JOptionPane.showMessageDialog(this, "Role Name already exists!");
            rsName.close();
            checkName.close();
            con.close();
            return;
        }
        rsName.close();
        checkName.close();

        // --- CHECK SAME SUBJECT + MIN SCORE COMBINATION FOR OTHER RECORDS ---
        PreparedStatement checkCombo = con.prepareStatement(
            "SELECT * FROM career_role WHERE role_name=? AND required_subject_id=? AND required_min_score=? AND role_id<>?");
        checkCombo.setString(1, roleName);
        checkCombo.setInt(2, subjectId);
        checkCombo.setInt(3, minScore);
        checkCombo.setInt(4, roleId);
        ResultSet rsCombo = checkCombo.executeQuery();
        if (rsCombo.next()) {
            JOptionPane.showMessageDialog(this, "This career with the same subject and minimum score already exists!");
            rsCombo.close();
            checkCombo.close();
            con.close();
            return;
        }
        rsCombo.close();
        checkCombo.close();

        // --- UPDATE DATABASE ---
        PreparedStatement ps = con.prepareStatement(
            "UPDATE career_role SET role_name=?, description=?, required_subject_id=?, required_min_score=? WHERE role_id=?");
        ps.setString(1, roleName);
        ps.setString(2, description);
        ps.setInt(3, subjectId);
        ps.setInt(4, minScore);
        ps.setInt(5, roleId);

        int updated = ps.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Career role updated successfully!");
            clearForm();
            loadCareerRoles();
        }

        ps.close();
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating career role: " + e.getMessage());
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        try {
            if (roleIdTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please search or select a career role first.");
                return;
            }

            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this career role?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

            if (confirm != JOptionPane.YES_OPTION) return;

            int roleId = Integer.parseInt(roleIdTxt.getText().trim());

            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");
            PreparedStatement ps = con.prepareStatement("DELETE FROM career_role WHERE role_id=?");
            ps.setInt(1, roleId);

            int deleted = ps.executeUpdate();
            if (deleted > 0) {
                JOptionPane.showMessageDialog(this, "Career role deleted successfully!");
                clearForm();
                loadCareerRoles();
            }

            ps.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error deleting career role: " + e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows
        loadSubjects();
        clearForm();

        try {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(
                "SELECT cr.role_id, cr.role_name, cr.description, s.subject_name, cr.required_min_score " +
                "FROM career_role cr " +
                "JOIN subjects s ON cr.required_subject_id = s.subject_id"
            );

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("role_id"),
                    rs.getString("role_name"),
                    rs.getString("description"),
                    rs.getString("subject_name"),
                    rs.getInt("required_min_score")
                });
            }

            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error retrieving career roles: " + e.getMessage());
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        try {
            if (searchTxt.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter Role ID to search.");
                return;
            }

            int searchId = Integer.parseInt(searchTxt.getText().trim());

            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");
            PreparedStatement ps = con.prepareStatement(
                "SELECT cr.role_id, cr.role_name, cr.description, s.subject_name, cr.required_min_score, s.subject_id " +
                "FROM career_role cr JOIN subjects s ON cr.required_subject_id = s.subject_id WHERE cr.role_id=?");
            ps.setInt(1, searchId);

            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                roleIdTxt.setText(String.valueOf(rs.getInt("role_id")));
                roleNameTxt.setText(rs.getString("role_name"));
                descriptionTxt.setText(rs.getString("description"));
                minScoreTxt.setText(String.valueOf(rs.getInt("required_min_score")));
                int subjId = rs.getInt("subject_id");
                String subjName = rs.getString("subject_name");
                String comboValue = subjId + " - " + subjName;

                // set combo selection
                for (int i = 0; i < requiredSubjectsCombo.getItemCount(); i++) {
                    if (requiredSubjectsCombo.getItemAt(i).equals(comboValue)) {
                        requiredSubjectsCombo.setSelectedIndex(i);
                        break;
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Career role not found!");
            }

            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching career role: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

     private void loadSubjects() {
        requiredSubjectsCombo.removeAllItems();
        try {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT subject_id, subject_name FROM subjects");

            while (rs.next()) {
                int id = rs.getInt("subject_id");
                String name = rs.getString("subject_name");
                requiredSubjectsCombo.addItem(id + " - " + name);
            }

            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading subjects: " + e.getMessage());
        }
    }

    private void loadCareerRoles() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/student_career_path_recommendation_system_db", "root", "password123");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(
                "SELECT cr.role_id, cr.role_name, cr.description, s.subject_name, cr.required_min_score " +
                "FROM career_role cr " +
                "JOIN subjects s ON cr.required_subject_id = s.subject_id");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("role_id"),
                    rs.getString("role_name"),
                    rs.getString("description"),
                    rs.getString("subject_name"),
                    rs.getInt("required_min_score")
                });
            }

            rs.close();
            stmt.close();
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading career roles: " + e.getMessage());
        }
    }

    private void clearForm() {
        roleIdTxt.setText("");
        roleNameTxt.setText("");
        descriptionTxt.setText("");
        minScoreTxt.setText("");
        requiredSubjectsCombo.setSelectedIndex(-1);
        searchTxt.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField minScoreTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JComboBox<String> requiredSubjectsCombo;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField roleIdTxt;
    private javax.swing.JTextField roleNameTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
