/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import model.Session;
import static model.Session.currentUser;
import model.User;


/**
 *
 * @author elie
 */
public class StudentDashboard extends javax.swing.JFrame {

    private StudentHomePanel homePanel;
    private StudentPerformancePage performancePage;
    private StudentRecommendationPage recommendationPage;
    private UpdateProfilePage profilePage;
    private javax.swing.JButton activeMenuButton;
    /**
     * Creates new form StudentDashboard
     */
    public StudentDashboard() {
        initComponents();
        applyRoleAccess();
        initCards();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setActiveMenuButton(homeBtn);
    }

   private void setActiveMenuButton(javax.swing.JButton button) {
    if (activeMenuButton != null) {
        // Reset old active button style
        activeMenuButton.setBackground(java.awt.Color.WHITE);
        activeMenuButton.setForeground(java.awt.Color.BLACK);
    }

    // Set new active button style
    activeMenuButton = button;
    //activeMenuButton.setBackground(new java.awt.Color(0, 153, 0)); // green
   
    activeMenuButton.setBackground(new java.awt.Color(0, 102, 153));
    activeMenuButton.setForeground(java.awt.Color.WHITE);
}
    StudentDashboard(User currentUser) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void initCards() {
        // 1) create panels
        homePanel = new StudentHomePanel();
        performancePage = new StudentPerformancePage();
        recommendationPage = new StudentRecommendationPage();
        profilePage = new UpdateProfilePage();
        
     // 2) add them to contentPanel with names
        contentPanel.add(homePanel, "home");
        contentPanel.add(performancePage,"performance");
        contentPanel.add(recommendationPage,"recommendation");
        contentPanel.add(profilePage, "profile");
        
  // 3) show a default card, e.g. students or a home panel
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
       cl.show(contentPanel, "home"); // or create a HomePanel and show "home"
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        performanceBtn = new javax.swing.JButton();
        recommendationBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 51));

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 105));
        jPanel2.setLayout(new java.awt.BorderLayout());

        headerPanel.setPreferredSize(new java.awt.Dimension(0, 105));
        headerPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 153));
        topPanel.setPreferredSize(new java.awt.Dimension(969, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/career1.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 102, 153));
        logoutBtn.setText("logout");
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Career Path Recommendation System");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Student Dashboard");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGap(368, 368, 368)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutBtn)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        headerPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setPreferredSize(new java.awt.Dimension(0, 40));
        menuPanel.setLayout(new java.awt.GridLayout());

        homeBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setPreferredSize(new java.awt.Dimension(59, 30));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        menuPanel.add(homeBtn);

        performanceBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        performanceBtn.setText("View Performance");
        performanceBtn.setPreferredSize(new java.awt.Dimension(157, 30));
        performanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceBtnActionPerformed(evt);
            }
        });
        menuPanel.add(performanceBtn);

        recommendationBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recommendationBtn.setText("View Recommendations");
        recommendationBtn.setPreferredSize(new java.awt.Dimension(197, 30));
        recommendationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationBtnActionPerformed(evt);
            }
        });
        menuPanel.add(recommendationBtn);

        profileBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        profileBtn.setText("update Profile");
        profileBtn.setPreferredSize(new java.awt.Dimension(129, 30));
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        menuPanel.add(profileBtn);

        headerPanel.add(menuPanel, java.awt.BorderLayout.CENTER);

        jPanel2.add(headerPanel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Close current window
            this.dispose();

            // Open login page again
            new LoginForm().setVisible(true);  // Change LoginPage to your actual login JFrame class name
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "home");
        setActiveMenuButton(homeBtn);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void performanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceBtnActionPerformed

        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "performance");
        setActiveMenuButton(performanceBtn);
    }//GEN-LAST:event_performanceBtnActionPerformed

    private void recommendationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "recommendation");
        setActiveMenuButton(recommendationBtn);
    }//GEN-LAST:event_recommendationBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed

        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "profile");
        setActiveMenuButton(profileBtn);
    }//GEN-LAST:event_profileBtnActionPerformed

// private void loadStudentInfo() {
//    jLabel2.setText("Full Name: " + Session.currentUserName);
//    jLabel3.setText("Email: " + Session.currentUserEmail);
//}

 private void applyRoleAccess() {
    if(Session.currentUserRole.equals("HOME")) {
       homeBtn.setVisible(false);   
       performanceBtn.setVisible(false);
    } 
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton performanceBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton recommendationBtn;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
