/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.SubjectDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Subject;
/**
 *
 * @author elie
 */
public class SubjectPage extends javax.swing.JPanel {

    /**
     * Creates new form SubjectPage
     */
    public SubjectPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        subjectIdTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        subjectNameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addTxt = new javax.swing.JButton();
        updateTxt = new javax.swing.JButton();
        deleteTxt = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        creditsTxt = new javax.swing.JTextField();
        levelTxt = new javax.swing.JTextField();
        descriptionTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        searchTXt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setBackground(new java.awt.Color(0, 102, 153));
        leftPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setBackground(new java.awt.Color(0, 102, 153));
        rightPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(rightPanel, java.awt.BorderLayout.LINE_END);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 340));

        jLabel1.setBackground(new java.awt.Color(0, 102, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Subject Form ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Subject ID");

        subjectIdTxt.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Subject Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Level");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Credits");

        addTxt.setBackground(new java.awt.Color(0, 0, 51));
        addTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addTxt.setForeground(new java.awt.Color(255, 255, 255));
        addTxt.setText("Add");
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });

        updateTxt.setBackground(new java.awt.Color(0, 0, 255));
        updateTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateTxt.setForeground(new java.awt.Color(255, 255, 255));
        updateTxt.setText("Update");
        updateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTxtActionPerformed(evt);
            }
        });

        deleteTxt.setBackground(new java.awt.Color(255, 0, 0));
        deleteTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteTxt.setForeground(new java.awt.Color(255, 255, 255));
        deleteTxt.setText("Delete");
        deleteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTxtActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(0, 51, 51));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111)
                        .addComponent(subjectIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshBtn))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                            .addComponent(creditsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(levelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(descriptionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(subjectNameTxt)))))
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(creditsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTxt)
                    .addComponent(updateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTxt)
                    .addComponent(refreshBtn))
                .addGap(40, 40, 40))
        );

        mainPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Registered Subjects");

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Subject Id", "Subject Name", "Description", "Level", "Credits"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(subjectTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchTXt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTXt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
                                       
                                      
    String subjectName = subjectNameTxt.getText().trim();
    String description = descriptionTxt.getText().trim();
    String level = levelTxt.getText().trim();
    String creditsStr = creditsTxt.getText().trim();

    // VALIDATIONS
    if (subjectName.isEmpty() || !subjectName.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Subject Name is required and must contain only letters!");
        subjectNameTxt.requestFocus();
        return;
    }

    // 🔥 NEW: check if subject name already exists
    SubjectDao dao = new SubjectDao(); // moved up
    if (dao.subjectNameExists(subjectName)) {
        JOptionPane.showMessageDialog(this, "This subject name already exists. Please choose another name.");
        subjectNameTxt.requestFocus();
        return;
    }

    if (description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Description is required!");
        descriptionTxt.requestFocus();
        return;
    }

    if (level.isEmpty() || !level.matches("(year [1-4]|semester [1-9]|semester 10)")) {
        JOptionPane.showMessageDialog(this, "Level must be 'year 1-4' or 'semester 1-10'");
        levelTxt.requestFocus();
        return;
    }

    int credits;
    try {
        credits = Integer.parseInt(creditsStr);
        if (credits <= 0) {
            JOptionPane.showMessageDialog(this, "Credits must be a positive number!");
            creditsTxt.requestFocus();
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Credits must be a valid number!");
        creditsTxt.requestFocus();
        return;
    }

    // CREATE SUBJECT OBJECT
    Subject s = new Subject();
    s.setSubjectName(subjectName);
    s.setDescription(description);
    s.setLevel(level);
    s.setCredits(credits);

    // SAVE TO DATABASE
    int result = dao.createSubject(s);  // reuse same dao

    if (result > 0) {
        JOptionPane.showMessageDialog(this, "Subject added successfully!");
        loadSubjectTable();
        clearFields();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add subject.");
    }

    }//GEN-LAST:event_addTxtActionPerformed

    private void updateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTxtActionPerformed
                                         

    String subjectIdStr = subjectIdTxt.getText().trim();
    String subjectName = subjectNameTxt.getText().trim();
    String description = descriptionTxt.getText().trim();
    String level = levelTxt.getText().trim();
    String creditsStr = creditsTxt.getText().trim();

    // VALIDATIONS
    if (subjectIdStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please select a subject to update!");
        return;
    }

    if (subjectName.isEmpty() || !subjectName.matches("[a-zA-Z ]+")) {
        JOptionPane.showMessageDialog(this, "Subject Name is required and must contain only letters!");
        subjectNameTxt.requestFocus();
        return;
    }

    int subjectId = Integer.parseInt(subjectIdStr);
    SubjectDao dao = new SubjectDao();

    // 🔥 NEW: check if another subject already uses this name
    if (dao.subjectNameExistsForOtherId(subjectName, subjectId)) {
        JOptionPane.showMessageDialog(this, "Another subject already has this name. Please choose a different name.");
        subjectNameTxt.requestFocus();
        return;
    }

    if (description.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Description is required!");
        descriptionTxt.requestFocus();
        return;
    }

    if (level.isEmpty() || !level.matches("(year [1-4]|semester [1-9]|semester 10)")) {
        JOptionPane.showMessageDialog(this, "Level must be 'year 1-4' or 'semester 1-10'");
        levelTxt.requestFocus();
        return;
    }

    int credits;
    try {
        credits = Integer.parseInt(creditsStr);
        if (credits <= 0) {
            JOptionPane.showMessageDialog(this, "Credits must be a positive number!");
            creditsTxt.requestFocus();
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Credits must be a valid number!");
        creditsTxt.requestFocus();
        return;
    }

    // UPDATE SUBJECT OBJECT
    Subject s = new Subject();
    s.setSubjectId(subjectId);
    s.setSubjectName(subjectName);
    s.setDescription(description);
    s.setLevel(level);
    s.setCredits(credits);

    // UPDATE DATABASE
    int result = dao.updateSubject(s);

    if (result > 0) {
        JOptionPane.showMessageDialog(this, "Subject updated successfully!");
        loadSubjectTable();
        clearFields();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to update subject.");
    }

    }//GEN-LAST:event_updateTxtActionPerformed

    private void deleteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTxtActionPerformed

        int id = Integer.parseInt(subjectIdTxt.getText());

        SubjectDao dao = new SubjectDao();
        int result = dao.deleteSubject(id);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Subject deleted successfully!");
            loadSubjectTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete subject.");
        }
    }//GEN-LAST:event_deleteTxtActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadSubjectTable();
        clearFields();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

        try {
            int id = Integer.parseInt(searchTXt.getText());

            SubjectDao dao = new SubjectDao();
            Subject s = dao.findSubjectById(id);

            if (s != null) {
                subjectIdTxt.setText(String.valueOf(s.getSubjectId()));
                subjectNameTxt.setText(s.getSubjectName());
                descriptionTxt.setText(s.getDescription());
                levelTxt.setText(s.getLevel());
                creditsTxt.setText(String.valueOf(s.getCredits()));
            } else {
                JOptionPane.showMessageDialog(this, "Subject not found.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Invalid ID format");
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void loadSubjectTable() {
    SubjectDao dao = new SubjectDao();
    List<Subject> list = dao.findAllSubjects();

    DefaultTableModel model = (DefaultTableModel) subjectTable.getModel();
    model.setRowCount(0);

    for (Subject s : list) {
        model.addRow(new Object[]{
            s.getSubjectId(),
            s.getSubjectName(),
            s.getDescription(),
            s.getLevel(),
            s.getCredits()
        });
    }
}
    private void clearFields() {
    subjectIdTxt.setText("");
    subjectNameTxt.setText("");
    descriptionTxt.setText("");
    levelTxt.setText("");
    creditsTxt.setText("");
    searchTXt.setText("");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxt;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JTextField creditsTxt;
    private javax.swing.JButton deleteTxt;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField levelTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTXt;
    private javax.swing.JTextField subjectIdTxt;
    private javax.swing.JTextField subjectNameTxt;
    private javax.swing.JTable subjectTable;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updateTxt;
    // End of variables declaration//GEN-END:variables
}
