/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import service.StudentService;
import service.UserService;

/**
 *
 * @author elie
 */
public class AdminHomePage extends javax.swing.JPanel {

     private Image backgroundImage;
      private UserService userService;
    private StudentService studentService;
    /**
     * Creates new form AdminHomePage
     */
    public AdminHomePage() {
        initComponents();
        // Load your image
        backgroundImage = new ImageIcon(getClass().getResource("/images/careerStudent.png")).getImage();
        setLayout(new BorderLayout()); // keeps it flexible
    }

      // Constructor used by AdminDashboard
    public AdminHomePage(UserService userService, StudentService studentService) {
        this.userService = userService;
        this.studentService = studentService;
        initComponents();
        backgroundImage = new ImageIcon(getClass().getResource("/images/careerStudent.png")).getImage();
        setLayout(new BorderLayout());

        // Now you can use userService and studentService to load data if needed
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        // draw the image to fill the panel
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/careerStudent.png"))); // NOI18N
        add(jLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
