/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Session;
import service.UserService;
import service.StudentService;
import javax.swing.JOptionPane;
import service.CareerRoleService;
import service.CompanyService;
import service.PerformanceService;
import service.SubjectService;


/**
 *
 * @author elie
 */
public class AdminDashboard extends javax.swing.JFrame {

     // RMI service references
    private UserService userService;
    private StudentService studentService;
    private SubjectService subjectService;
    private PerformanceService performanceService;
    private CareerRoleService careerRoleService;
    private CompanyService companyService;

    // Dashboard pages
    private AdminHomePage homePanel;
    private StudentPage studentPage;
    private SubjectPage subjectPage; 
    private PerformancePage performancePage;
    private CareerRolePage careerRolePage;
    private CompanyPage companyPage;
    private RecommendationPage recommendationPage;

    // Default constructor (optional if you still want it)
    
    public AdminDashboard() {
        initComponents();
         setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        initCards();
    }
    
    
  public AdminDashboard(UserService userService, StudentService studentService,
                      SubjectService subjectService, PerformanceService performanceService,
                      CareerRoleService careerRoleService, CompanyService companyService) {

    this.userService = userService;
    this.studentService = studentService;
    this.subjectService = subjectService;
    this.performanceService = performanceService;
    this.careerRoleService = careerRoleService;
    this.companyService = companyService;
  setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    initComponents();
    initCards();
}

  private void initCards() {
    // Existing panels
    homePanel = new AdminHomePage(userService, studentService);
    studentPage = new StudentPage(userService, studentService);
    subjectPage = new SubjectPage(subjectService);
    performancePage = new PerformancePage(performanceService, subjectService, studentService);
    careerRolePage = new CareerRolePage(careerRoleService, subjectService);
    companyPage = new CompanyPage(companyService, careerRoleService);
    recommendationPage = new RecommendationPage(careerRoleService);

    // Add panels to CardLayout
    contentPanel.add(homePanel, "home");
    contentPanel.add(studentPage, "students");
    contentPanel.add(subjectPage, "subjects");
    contentPanel.add(performancePage, "performance");
    contentPanel.add(careerRolePage, "careerRoles");
    contentPanel.add(companyPage, "companies");
    contentPanel.add(recommendationPage, "recommendations");

    // Show default card
    java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel, "home");
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        headerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        studentBtn = new javax.swing.JButton();
        subjectBtn = new javax.swing.JButton();
        performanceBtn = new javax.swing.JButton();
        careerRoleBtn = new javax.swing.JButton();
        companiesBtn = new javax.swing.JButton();
        recommendationBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setPreferredSize(new java.awt.Dimension(0, 105));
        headerPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 153));
        topPanel.setPreferredSize(new java.awt.Dimension(969, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/career1.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 102, 153));
        logoutBtn.setText("logout");
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Career Path Recommendation System");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Admin Dashboard");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)))
                .addGap(368, 368, 368)
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topPanelLayout.createSequentialGroup()
                        .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logoutBtn)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        headerPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        menuPanel.setBackground(new java.awt.Color(0, 0, 0));
        menuPanel.setPreferredSize(new java.awt.Dimension(0, 40));
        menuPanel.setLayout(new java.awt.GridLayout());

        homeBtn.setBackground(new java.awt.Color(255, 255, 255));
        homeBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        homeBtn.setText("Home ");
        homeBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        menuPanel.add(homeBtn);

        studentBtn.setBackground(new java.awt.Color(255, 255, 255));
        studentBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentBtn.setText("Manage Students");
        studentBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        studentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentBtnActionPerformed(evt);
            }
        });
        menuPanel.add(studentBtn);

        subjectBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subjectBtn.setText("Manage Subjects");
        subjectBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        subjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectBtnActionPerformed(evt);
            }
        });
        menuPanel.add(subjectBtn);

        performanceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        performanceBtn.setText("Manage Performance");
        performanceBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        performanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceBtnActionPerformed(evt);
            }
        });
        menuPanel.add(performanceBtn);

        careerRoleBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        careerRoleBtn.setText("Manage Career Role");
        careerRoleBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        careerRoleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                careerRoleBtnActionPerformed(evt);
            }
        });
        menuPanel.add(careerRoleBtn);

        companiesBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        companiesBtn.setText("Manage Companies");
        companiesBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        companiesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companiesBtnActionPerformed(evt);
            }
        });
        menuPanel.add(companiesBtn);

        recommendationBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        recommendationBtn.setText(" Recommendations ");
        recommendationBtn.setPreferredSize(new java.awt.Dimension(163, 30));
        recommendationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recommendationBtnActionPerformed(evt);
            }
        });
        menuPanel.add(recommendationBtn);

        headerPanel.add(menuPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "home");
       // setActiveMenuButton(homeBtn);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void studentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentBtnActionPerformed

        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "students");
        //setActiveMenuButton(studentBtn);
    }//GEN-LAST:event_studentBtnActionPerformed

    private void subjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "subjects");
        //setActiveMenuButton(subjectBtn);
    }//GEN-LAST:event_subjectBtnActionPerformed

    private void performanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "performance");
        //setActiveMenuButton(performanceBtn);
    }//GEN-LAST:event_performanceBtnActionPerformed

    private void careerRoleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_careerRoleBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "careerRoles");
        //setActiveMenuButton(careerRoleBtn);
    }//GEN-LAST:event_careerRoleBtnActionPerformed

    private void companiesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companiesBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "companies");
        //setActiveMenuButton(companiesBtn);
    }//GEN-LAST:event_companiesBtnActionPerformed

    private void recommendationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recommendationBtnActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) contentPanel.getLayout();
        cl.show(contentPanel, "recommendations");
        //setActiveMenuButton(recommendationBtn);
    }//GEN-LAST:event_recommendationBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            // Close current window
            this.dispose();

            // Open login page again
            new LoginForm().setVisible(true);  // Change LoginPage to your actual login JFrame class name
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void applyRoleAccess() {
    if(Session.currentUserRole.equals("HOME")) {
        homeBtn.setVisible(false);
        studentBtn.setVisible(false);       // hide manage students
        subjectBtn.setVisible(false);       // hide manage subjects
        performanceBtn.setVisible(false);   // hide manage performance
        careerRoleBtn.setVisible(false);    // hide manage career roles
        companiesBtn.setVisible(false);     // hide manage companies
    }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton careerRoleBtn;
    private javax.swing.JButton companiesBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton performanceBtn;
    private javax.swing.JButton recommendationBtn;
    private javax.swing.JButton studentBtn;
    private javax.swing.JButton subjectBtn;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
