/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.RemoteException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import dto.CareerRoleDTO;
import java.io.File;
import java.io.FileWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Subject;
import service.CareerRoleService;
import service.SubjectService;
/**
 *
 * @author elie
 */
public class CareerRolePage extends javax.swing.JPanel {

    // Service references
private CareerRoleService careerRoleService;
private SubjectService subjectService;

    /**
     * Creates new form CareerRolePage
     */
    public CareerRolePage(CareerRoleService careerRoleService, SubjectService subjectService) {
        initComponents();
        this.careerRoleService = careerRoleService;
        this.subjectService = subjectService;
         loadSubjects();
         
        loadCareerRoles();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roleIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        roleNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        minScoreTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        requiredSubjectsCombo = new javax.swing.JComboBox<>();
        descriptionTxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        csvBtn = new javax.swing.JButton();
        excelBtn = new javax.swing.JButton();
        pdtBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1368, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel1.add(rightPanel, java.awt.BorderLayout.LINE_END);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 381));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Career Role Form");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Role ID");

        roleIdTxt.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Role Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");

        addBtn.setBackground(new java.awt.Color(0, 0, 51));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(0, 51, 51));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Required min score");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Required Subjects");

        requiredSubjectsCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(135, 135, 135))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(requiredSubjectsCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(roleNameTxt)
                            .addComponent(roleIdTxt)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(72, 72, 72)
                            .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(24, 24, 24)
                            .addComponent(minScoreTxt))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(addBtn)
                            .addGap(18, 18, 18)
                            .addComponent(updateBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(deleteBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(refreshBtn))))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roleIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(roleNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requiredSubjectsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(minScoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addGap(26, 26, 26))
        );

        mainPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Lists of Career Roles");

        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Role ID", "Role Name", "Description", "Required Subjects", "Required min score"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        csvBtn.setText("export csv");
        csvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvBtnActionPerformed(evt);
            }
        });

        excelBtn.setText("export excel");
        excelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBtnActionPerformed(evt);
            }
        });

        pdtBtn.setText("export pdf");
        pdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdtBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(searchTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(csvBtn)
                                .addGap(52, 52, 52)
                                .addComponent(excelBtn)
                                .addGap(66, 66, 66)
                                .addComponent(pdtBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csvBtn)
                    .addComponent(excelBtn)
                    .addComponent(pdtBtn))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
                                      
    try {
        // --- GET FORM VALUES ---
        String roleName = roleNameTxt.getText().trim();
        String description = descriptionTxt.getText().trim();
        String minScoreStr = minScoreTxt.getText().trim();
        String selectedSubjectStr = (String) requiredSubjectsCombo.getSelectedItem();

        // --- VALIDATIONS ---
        if (roleName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Role Name cannot be empty.");
            return;
        }
        if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Description cannot be empty.");
            return;
        }
        if (minScoreStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Minimum score cannot be empty.");
            return;
        }

        int minScore;
        try {
            minScore = Integer.parseInt(minScoreStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Minimum score must be a valid number.");
            return;
        }
        if (minScore < 60) {
            JOptionPane.showMessageDialog(this, "Minimum score must be at least 60.");
            return;
        }
        if (selectedSubjectStr == null || selectedSubjectStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a required subject.");
            return;
        }

        // --- Convert selected subject string to ID + Name ---
        String[] parts = selectedSubjectStr.split(" - ", 2);
        int subjectId = Integer.parseInt(parts[0]);
        String subjectName = (parts.length > 1) ? parts[1].trim() : "";

        List<Integer> subjectIds = new ArrayList<>();
        subjectIds.add(subjectId);
        List<String> subjectNames = new ArrayList<>();
        subjectNames.add(subjectName);

        // --- CREATE CareerRoleDTO ---
        CareerRoleDTO cr = new CareerRoleDTO();
        cr.setRoleName(roleName);
        cr.setDescription(description);
        cr.setRequiredMinScore(minScore);
        cr.setRequiredSubjectIds(subjectIds);
        cr.setRequiredSubjectNames(subjectNames);

        // --- CALL SERVICE TO ADD ---
        careerRoleService.addCareerRole(cr); // RMI call
        JOptionPane.showMessageDialog(this, "Career role added successfully!");

        clearForm();
        loadCareerRoles();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding career role: " + e.getMessage());
    }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
                                         
    try {
        if (roleIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search or select a career role first.");
            return;
        }

        String roleName = roleNameTxt.getText().trim();
        String description = descriptionTxt.getText().trim();
        String minScoreStr = minScoreTxt.getText().trim();
        String selectedSubjectStr = (String) requiredSubjectsCombo.getSelectedItem();
        int roleId = Integer.parseInt(roleIdTxt.getText().trim());

        // --- VALIDATIONS ---
        if (roleName.isEmpty() || description.isEmpty() || minScoreStr.isEmpty() || selectedSubjectStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        int minScore;
        try {
            minScore = Integer.parseInt(minScoreStr);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Minimum score must be a valid number.");
            return;
        }
        if (minScore < 60) {
            JOptionPane.showMessageDialog(this, "Minimum score must be at least 60.");
            return;
        }

        // --- Convert selected subject string to ID + Name ---
        String[] parts = selectedSubjectStr.split(" - ", 2);
        int subjectId = Integer.parseInt(parts[0]);
        String subjectName = (parts.length > 1) ? parts[1].trim() : "";

        List<Integer> subjectIds = new ArrayList<>();
        subjectIds.add(subjectId);
        List<String> subjectNames = new ArrayList<>();
        subjectNames.add(subjectName);

        // --- CREATE CareerRoleDTO FOR UPDATE ---
        CareerRoleDTO cr = new CareerRoleDTO();
        cr.setRoleId(roleId);
        cr.setRoleName(roleName);
        cr.setDescription(description);
        cr.setRequiredMinScore(minScore);
        cr.setRequiredSubjectIds(subjectIds);
        cr.setRequiredSubjectNames(subjectNames);

        // --- CALL SERVICE TO UPDATE ---
        careerRoleService.updateCareerRole(cr); // RMI call
        JOptionPane.showMessageDialog(this, "Career role updated successfully!");

        clearForm();
        loadCareerRoles();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating career role: " + e.getMessage());
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
                                         
    try {
        if (roleIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a career role first.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this career role?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        int roleId = Integer.parseInt(roleIdTxt.getText().trim());
        CareerRoleDTO cr = new CareerRoleDTO();
        cr.setRoleId(roleId);

        CareerRoleDTO deleted = careerRoleService.deleteCareerRole(cr);
        if (deleted != null) {
            JOptionPane.showMessageDialog(this, "Career role deleted successfully!");
            clearForm();
            loadCareerRoles();
        }

    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error deleting career role: " + e.getMessage());
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed

        loadCareerRoles();
        clearForm();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
                                          
    try {
        if (searchTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Role ID to search.");
            return;
        }

        int searchId = Integer.parseInt(searchTxt.getText().trim());
        CareerRoleDTO cr = careerRoleService.findCareerRoleById(searchId); // RMI call

        if (cr != null) {
            roleIdTxt.setText(String.valueOf(cr.getRoleId()));
            roleNameTxt.setText(cr.getRoleName());
            descriptionTxt.setText(cr.getDescription());
            minScoreTxt.setText(String.valueOf(cr.getRequiredMinScore()));

            // --- Select first required subject (if any) ---
            if (cr.getRequiredSubjectIds() != null && !cr.getRequiredSubjectIds().isEmpty()) {
                int subjectId = cr.getRequiredSubjectIds().get(0);
                for (int i = 0; i < requiredSubjectsCombo.getItemCount(); i++) {
                    String item = requiredSubjectsCombo.getItemAt(i);
                    if (item == null) continue;
                    String[] parts = item.split(" - ", 2);
                    if (parts.length == 0) continue;
                    try {
                        int itemId = Integer.parseInt(parts[0]);
                        if (itemId == subjectId) {
                            requiredSubjectsCombo.setSelectedIndex(i);
                            break;
                        }
                    } catch (NumberFormatException ignore) {
                        // ignore
                    }
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Career role not found!");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid Role ID.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error searching career role: " + e.getMessage());
    }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void csvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvBtnActionPerformed
                    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this,
                "No subject data to export",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    exportTableToCSV(jTable1);
    }//GEN-LAST:event_csvBtnActionPerformed

    private void excelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBtnActionPerformed
        JOptionPane.showMessageDialog(this,
            "Excel export uses CSV format. Please use 'Export CSV' and open it with Excel.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_excelBtnActionPerformed

    private void pdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdtBtnActionPerformed
         JOptionPane.showMessageDialog(this,
            "PDF export module is available and can be enabled using iText library.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pdtBtnActionPerformed

    private void loadSubjects() {
    requiredSubjectsCombo.removeAllItems();
    try {
        List<Subject> subjects = subjectService.retrieveAllSubjects();
        for (Subject s : subjects) {
            requiredSubjectsCombo.addItem(s.getSubjectId() + " - " + s.getSubjectName());
        }
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error loading subjects: " + e.getMessage());
    }
}

private void loadCareerRoles() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    try {
        List<CareerRoleDTO> roles = careerRoleService.retrieveAllCareerRoles();

        for (CareerRoleDTO cr : roles) {
            String subjectsText = "Unknown";
            if (cr.getRequiredSubjectNames() != null && !cr.getRequiredSubjectNames().isEmpty()) {
                StringBuilder sb = new StringBuilder();
                for (String n : cr.getRequiredSubjectNames()) {
                    if (n == null || n.trim().isEmpty()) continue;
                    if (sb.length() > 0) sb.append(", ");
                    sb.append(n.trim());
                }
                if (sb.length() > 0) subjectsText = sb.toString();
            }

            model.addRow(new Object[]{
                cr.getRoleId(),
                cr.getRoleName(),
                cr.getDescription(),
                subjectsText,
                cr.getRequiredMinScore()
            });
        }

    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error loading career roles: " + e.getMessage());
    }
}



    private void clearForm() {
        roleIdTxt.setText("");
        roleNameTxt.setText("");
        descriptionTxt.setText("");
        minScoreTxt.setText("");
        requiredSubjectsCombo.setSelectedIndex(-1);
        searchTxt.setText("");
    }

    private void exportTableToCSV(JTable table) {
    JFileChooser chooser = new JFileChooser();
    chooser.setSelectedFile(new File("careerRole_report.csv"));

    if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try (FileWriter fw = new FileWriter(file)) {

            // Write column headers
            for (int i = 0; i < table.getColumnCount(); i++) {
                fw.write(table.getColumnName(i) + ",");
            }
            fw.write("\n");

            // Write table rows
            for (int i = 0; i < table.getRowCount(); i++) {
                for (int j = 0; j < table.getColumnCount(); j++) {
                    Object value = table.getValueAt(i, j);
                    fw.write((value != null ? value.toString() : "") + ",");
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this,
                    "Career Role report exported successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to export report: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
    
    @Override
public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);
    if (aFlag) {
       loadCareerRoles();
       loadSubjects();
    }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton csvBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JButton excelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField minScoreTxt;
    private javax.swing.JButton pdtBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JComboBox<String> requiredSubjectsCombo;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField roleIdTxt;
    private javax.swing.JTextField roleNameTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
