/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dto.CareerRoleDTO;
import dto.CompanyDTO;
import java.io.File;
import java.io.FileWriter;
import service.CompanyService;
import service.CareerRoleService;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.rmi.RemoteException;
import java.util.List;

/**
 *
 * @author elie
 */
public class CompanyPage extends javax.swing.JPanel {

     // Service objects
    private CompanyService companyService;
    private CareerRoleService careerRoleService;
    /**
     * Creates new form CompanyPage
     */
    public CompanyPage(CompanyService companyService, CareerRoleService careerRoleService) {
        this.companyService = companyService;
        this.careerRoleService = careerRoleService;
        initComponents();
        loadCareerRoles();
        showCompaniesInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        companyIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companyNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        descriptionTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        careerRoleCombo = new javax.swing.JComboBox<>();
        refreshBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        csvBtn = new javax.swing.JButton();
        excelBtn = new javax.swing.JButton();
        pdfBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        bottomPanel.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        leftPanel.setBackground(new java.awt.Color(0, 102, 153));
        leftPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        rightPanel.setBackground(new java.awt.Color(0, 102, 153));
        rightPanel.setPreferredSize(new java.awt.Dimension(250, 370));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(rightPanel, java.awt.BorderLayout.LINE_END);

        mainPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 380));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Company Form");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Company ID");

        companyIdTxt.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Company Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Career Role");

        addBtn.setBackground(new java.awt.Color(0, 0, 51));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Description");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Location");

        careerRoleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(83, 83, 83)
                                .addComponent(companyNameTxt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(102, 102, 102)
                                .addComponent(companyIdTxt))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addBtn)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(locationTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(descriptionTxt)
                                            .addComponent(careerRoleCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(updateBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(deleteBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(refreshBtn)
                                        .addGap(0, 14, Short.MAX_VALUE)))))))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(descriptionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(companyIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(companyNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(careerRoleCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(66, 66, 66))
        );

        mainPanel.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("List of Companies");

        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company ID", "Company Name", "Career Role", "Location", "Descrption"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        csvBtn.setText("export csv");
        csvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvBtnActionPerformed(evt);
            }
        });

        excelBtn.setText("export excel");
        excelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBtnActionPerformed(evt);
            }
        });

        pdfBtn.setText("export pdf");
        pdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(searchTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(csvBtn)
                .addGap(60, 60, 60)
                .addComponent(excelBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pdfBtn)
                .addGap(98, 98, 98))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csvBtn)
                    .addComponent(excelBtn)
                    .addComponent(pdfBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(mainPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
                                       
    try {
        String name = companyNameTxt.getText().trim();
        String loc = locationTxt.getText().trim();
        String desc = descriptionTxt.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Company name is required.");
            companyNameTxt.requestFocus();
            return;
        }

        if (careerRoleCombo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a career role.");
            return;
        }

        String selected = careerRoleCombo.getSelectedItem().toString();
        String[] roleParts = selected.split(" - ", 2);
        int roleId = Integer.parseInt(roleParts[0]);

        CareerRoleDTO roleDto = careerRoleService.findCareerRoleById(roleId);
        String roleName = (roleDto != null && roleDto.getRoleName() != null)
                ? roleDto.getRoleName()
                : (roleParts.length > 1 ? roleParts[1].trim() : null);

        CompanyDTO c = new CompanyDTO();
        c.setCompanyName(name);
        c.setLocation(loc);
        c.setDescription(desc);
        c.setCareerRoleId(roleId);
        c.setCareerRoleName(roleName);

        companyService.saveCompany(c);

        showCompaniesInTable();
        clearForm();
        JOptionPane.showMessageDialog(this, "Company added successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error adding company: " + e.getMessage());
    }
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
                                          
    try {
        if (companyIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search or select a company first.");
            return;
        }

        int id = Integer.parseInt(companyIdTxt.getText().trim());
        String name = companyNameTxt.getText().trim();
        String loc = locationTxt.getText().trim();
        String desc = descriptionTxt.getText().trim();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Company name is required.");
            companyNameTxt.requestFocus();
            return;
        }

        if (careerRoleCombo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a career role.");
            return;
        }

        String selected = careerRoleCombo.getSelectedItem().toString();
        String[] roleParts = selected.split(" - ", 2);
        int roleId = Integer.parseInt(roleParts[0]);

        CareerRoleDTO roleDto = careerRoleService.findCareerRoleById(roleId);
        String roleName = (roleDto != null && roleDto.getRoleName() != null)
                ? roleDto.getRoleName()
                : (roleParts.length > 1 ? roleParts[1].trim() : null);

        CompanyDTO c = new CompanyDTO();
        c.setCompanyId(id);
        c.setCompanyName(name);
        c.setLocation(loc);
        c.setDescription(desc);
        c.setCareerRoleId(roleId);
        c.setCareerRoleName(roleName);

        companyService.updateCompany(c);

        showCompaniesInTable();
        clearForm();
        JOptionPane.showMessageDialog(this, "Company updated successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error updating company: " + e.getMessage());
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
                                         
    try {
        if (companyIdTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search or select a company first.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this company?",
            "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        int id = Integer.parseInt(companyIdTxt.getText().trim());
        CompanyDTO c = new CompanyDTO();
        c.setCompanyId(id);
        companyService.deleteCompany(c);

        showCompaniesInTable();
        clearForm();
        JOptionPane.showMessageDialog(this, "Company deleted successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error deleting company: " + e.getMessage());
    }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
                                         
    try {
        if (searchTxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Company ID to search.");
            return;
        }

        int id = Integer.parseInt(searchTxt.getText().trim());
        CompanyDTO c = companyService.searchCompanyById(id);

        if (c != null) {
            companyIdTxt.setText(String.valueOf(c.getCompanyId()));
            companyNameTxt.setText(c.getCompanyName());
            locationTxt.setText(c.getLocation());
            descriptionTxt.setText(c.getDescription());

            // set combo by roleId (best) or by full text
            int roleId = c.getCareerRoleId();
            for (int i = 0; i < careerRoleCombo.getItemCount(); i++) {
                String item = careerRoleCombo.getItemAt(i);
                if (item == null) continue;
                String[] parts = item.split(" - ", 2);
                if (parts.length == 0) continue;
                try {
                    int itemId = Integer.parseInt(parts[0]);
                    if (itemId == roleId) {
                        careerRoleCombo.setSelectedIndex(i);
                        break;
                    }
                } catch (NumberFormatException ignore) {
                    // ignore
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Company not found!");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Company ID.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error searching company: " + e.getMessage());
    }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        clearForm();
        loadCareerRoles();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void csvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvBtnActionPerformed
                    if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this,
                "No subject data to export",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    exportTableToCSV(jTable1);
    }//GEN-LAST:event_csvBtnActionPerformed

    private void excelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBtnActionPerformed
      JOptionPane.showMessageDialog(this,
            "Excel export uses CSV format. Please use 'Export CSV' and open it with Excel.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_excelBtnActionPerformed

    private void pdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBtnActionPerformed
         JOptionPane.showMessageDialog(this,
            "PDF export module is available and can be enabled using iText library.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pdfBtnActionPerformed

  private void loadCareerRoles() {
    careerRoleCombo.removeAllItems();
    try {
        List<CareerRoleDTO> roles = careerRoleService.retrieveAllCareerRoles();
        for (CareerRoleDTO cr : roles) {
            careerRoleCombo.addItem(cr.getRoleId() + " - " + cr.getRoleName());
        }
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error loading career roles: " + e.getMessage());
    }
}

  private void showCompaniesInTable() {
    try {
        List<CompanyDTO> companies = companyService.retrieveAllCompanies();
        String[] columns = {"ID", "Company Name", "Career Role", "Location", "Description"};
        Object[][] data = new Object[companies.size()][5];

        for (int i = 0; i < companies.size(); i++) {
            CompanyDTO c = companies.get(i);
            data[i][0] = c.getCompanyId();
            data[i][1] = c.getCompanyName();
            data[i][2] = (c.getCareerRoleName() != null && !c.getCareerRoleName().trim().isEmpty())
                    ? c.getCareerRoleName()
                    : "Unknown";
            data[i][3] = c.getLocation();
            data[i][4] = c.getDescription();
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columns) {
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        });
//    } catch (RemoteException e) {
//        JOptionPane.showMessageDialog(this, "Error loading companies: " + e.getMessage());
//    }

} catch (Exception e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(this, "Error loading companies: " + e);
}
}

    
  
    private void clearForm() {
        companyIdTxt.setText("");
        companyNameTxt.setText("");
        locationTxt.setText("");
        descriptionTxt.setText("");
        careerRoleCombo.setSelectedIndex(-1);
        searchTxt.setText("");
    }
    
    private void exportTableToCSV(JTable table) {
    JFileChooser chooser = new JFileChooser();
    chooser.setSelectedFile(new File("company_report.csv"));

    if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try (FileWriter fw = new FileWriter(file)) {

            // Write column headers
            for (int i = 0; i < table.getColumnCount(); i++) {
                fw.write(table.getColumnName(i) + ",");
            }
            fw.write("\n");

            // Write table rows
            for (int i = 0; i < table.getRowCount(); i++) {
                for (int j = 0; j < table.getColumnCount(); j++) {
                    Object value = table.getValueAt(i, j);
                    fw.write((value != null ? value.toString() : "") + ",");
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this,
                    "Company report exported successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to export report: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JComboBox<String> careerRoleCombo;
    private javax.swing.JTextField companyIdTxt;
    private javax.swing.JTextField companyNameTxt;
    private javax.swing.JButton csvBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField descriptionTxt;
    private javax.swing.JButton excelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pdfBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel topPanel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
