/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.RemoteException;
import java.util.List;
import dto.PerformanceDTO;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Student;
import model.Subject;
import service.PerformanceService;
import service.StudentService;
import service.SubjectService;
/**
 *
 * @author elie
 */
public class PerformancePage extends javax.swing.JPanel {

    private PerformanceService performanceService;
    private StudentService studentService;
    private SubjectService subjectService;
    
    /**
     * Creates new form PerformancePage
     */
    public PerformancePage(PerformanceService performanceService,SubjectService subjectService ,StudentService studentService) {
        initComponents();
        this.performanceService = performanceService;
        this.subjectService = subjectService;
        this.studentService = studentService;        
    
        loadStudentAndSubject();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        searchTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        searchBtn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        csvBtn = new javax.swing.JButton();
        excelBtn = new javax.swing.JButton();
        pdfBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        performanceIdTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        studentCombo = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        gradeTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        scoreTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        subjectCombo = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Registered Performance");

        searchBtn4.setText("search");
        searchBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtn4ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Performance ID", "Student Name", "Subject Name", "Score", "Grade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        csvBtn.setText("export csv");
        csvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvBtnActionPerformed(evt);
            }
        });

        excelBtn.setText("export excel");
        excelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelBtnActionPerformed(evt);
            }
        });

        pdfBtn.setText("export pdf");
        pdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(searchTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchBtn4))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(csvBtn)
                        .addGap(61, 61, 61)
                        .addComponent(excelBtn)
                        .addGap(68, 68, 68)
                        .addComponent(pdfBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(csvBtn)
                    .addComponent(excelBtn)
                    .addComponent(pdfBtn))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Performance Page");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 377));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Performance Form");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Performance Id");

        performanceIdTxt.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("student Id");

        studentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        registerBtn.setBackground(new java.awt.Color(0, 0, 51));
        registerBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("add");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 255));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setBackground(new java.awt.Color(0, 51, 51));
        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(255, 255, 255));
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Grade");

        gradeTxt.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Score");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Subject Id");

        subjectCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(registerBtn)
                                .addGap(18, 18, 18)
                                .addComponent(updateBtn)
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn)
                                .addGap(18, 18, 18)
                                .addComponent(refreshBtn))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gradeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(studentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(42, 42, 42)
                                    .addComponent(performanceIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(performanceIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(studentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(subjectCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scoreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(gradeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(updateBtn)
                    .addComponent(deleteBtn)
                    .addComponent(refreshBtn))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1369, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(154, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE)))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 878, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
        );

        add(jPanel10, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtn4ActionPerformed
   
    try {
        if (searchTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Performance ID to search.");
            return;
        }

        int id = Integer.parseInt(searchTxt.getText());
        PerformanceDTO p = performanceService.findPerformanceById(id);

        if (p != null) {
            performanceIdTxt.setText(String.valueOf(p.getPerformanceId()));

            // Select student
            for (int i = 0; i < studentCombo.getItemCount(); i++) {
                int studentId = Integer.parseInt(studentCombo.getItemAt(i).split(" - ")[0]);
                if (studentId == p.getStudentId()) {
                    studentCombo.setSelectedIndex(i);
                    break;
                }
            }

            // Select subject
            for (int i = 0; i < subjectCombo.getItemCount(); i++) {
                int subjectId = Integer.parseInt(subjectCombo.getItemAt(i).split(" - ")[0]);
                if (subjectId == p.getSubjectId()) {
                    subjectCombo.setSelectedIndex(i);
                    break;
                }
            }

            scoreTxt.setText(String.valueOf(p.getScore()));
            gradeTxt.setText(p.getGrade());

        } else {
            JOptionPane.showMessageDialog(this, "Performance not found.");
            clearFields();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Enter a valid Performance ID.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error searching performance: " + e.getMessage());
    }
    }//GEN-LAST:event_searchBtn4ActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed

    try {
        // Validate selections
        if (studentCombo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a Student.");
            return;
        }
        if (subjectCombo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select a Subject.");
            return;
        }
        if (scoreTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Score.");
            return;
        }

        double score = Double.parseDouble(scoreTxt.getText());
        if (score < 0 || score > 100) {
            JOptionPane.showMessageDialog(this, "Score must be between 0 and 100.");
            return;
        }

        int studentId = Integer.parseInt(((String) studentCombo.getSelectedItem()).split(" - ")[0]);
        int subjectId = Integer.parseInt(((String) subjectCombo.getSelectedItem()).split(" - ")[0]);

        // Check duplicate
        List<PerformanceDTO> existing = performanceService.getPerformancesByStudentId(studentId);
        if (existing != null) {
            for (PerformanceDTO existingPerf : existing) {
                if (existingPerf != null && existingPerf.getSubjectId() == subjectId) {
                    JOptionPane.showMessageDialog(this, "This student already has a score for this subject.");
                    return;
                }
            }
        }

        // Create Performance
        PerformanceDTO p = new PerformanceDTO();
        p.setStudentId(studentId);
        p.setSubjectId(subjectId);
        p.setScore(score);
        p.setGrade(calculateGrade(score));

        PerformanceDTO added = performanceService.addPerformance(p);
        if (added != null) {
            JOptionPane.showMessageDialog(this, "Performance added successfully!");
            clearFields();
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add performance.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Score must be a valid number.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error adding performance: " + e.getMessage());
    }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

    try {
        if (performanceIdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please search and select a performance first.");
            return;
        }
        if (studentCombo.getSelectedItem() == null || subjectCombo.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please select Student and Subject.");
            return;
        }
        if (scoreTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter the Score.");
            return;
        }

        int performanceId = Integer.parseInt(performanceIdTxt.getText());
        int studentId = Integer.parseInt(((String) studentCombo.getSelectedItem()).split(" - ")[0]);
        int subjectId = Integer.parseInt(((String) subjectCombo.getSelectedItem()).split(" - ")[0]);
        double score = Double.parseDouble(scoreTxt.getText());

        PerformanceDTO old = performanceService.findPerformanceById(performanceId);
        if (old != null && (old.getStudentId() != studentId || old.getSubjectId() != subjectId)) {
            List<PerformanceDTO> existing = performanceService.getPerformancesByStudentId(studentId);
            if (existing != null) {
                for (PerformanceDTO existingPerf : existing) {
                    if (existingPerf != null && existingPerf.getSubjectId() == subjectId) {
                        JOptionPane.showMessageDialog(this, "This student already has a score for this subject.");
                        return;
                    }
                }
            }
        }

        PerformanceDTO updated = new PerformanceDTO();
        updated.setPerformanceId(performanceId);
        updated.setStudentId(studentId);
        updated.setSubjectId(subjectId);
        updated.setScore(score);
        updated.setGrade(calculateGrade(score));

        PerformanceDTO result = performanceService.updatePerformance(updated);
        if (result != null) {
            JOptionPane.showMessageDialog(this, "Performance updated successfully!");
            clearFields();
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update performance.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Score must be a valid number.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error updating performance: " + e.getMessage());
    }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
   
    try {
        if (performanceIdTxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a performance to delete.");
            return;
        }

        int performanceId = Integer.parseInt(performanceIdTxt.getText());
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", "Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        PerformanceDTO toDelete = new PerformanceDTO();
        toDelete.setPerformanceId(performanceId);
        PerformanceDTO deleted = performanceService.deletePerformance(toDelete);

        if (deleted != null) {
            JOptionPane.showMessageDialog(this, "Performance deleted successfully!");
            clearFields();
            loadTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete performance.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid Performance ID.");
    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Error deleting performance: " + e.getMessage());
    }
    
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        loadTable();
        clearFields();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void csvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvBtnActionPerformed
                   if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this,
                "No subject data to export",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
    exportTableToCSV(jTable1);
    }//GEN-LAST:event_csvBtnActionPerformed

    private void excelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelBtnActionPerformed
        JOptionPane.showMessageDialog(this,
            "Excel export uses CSV format. Please use 'Export CSV' and open it with Excel.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_excelBtnActionPerformed

    private void pdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBtnActionPerformed
         JOptionPane.showMessageDialog(this,
            "PDF export module is available and can be enabled using iText library.",
            "Information",
            JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_pdfBtnActionPerformed

 
    private String calculateGrade(double score) {
    if(score >= 90) return "A";
    else if(score >= 80) return "B";
    else if(score >= 70) return "C";
    else if(score >= 60) return "D";
    else return "F";
}

// Clear input fields and reload combos
private void clearFields() {
    performanceIdTxt.setText("");    
    scoreTxt.setText("");
    gradeTxt.setText("");
    searchTxt.setText("");
    loadStudentAndSubject();
    
}



// LOAD STUDENTS AND SUBJECTS
private void loadStudentAndSubject() {
    try {
        // Load students
        List<Student> students = studentService.retrieveAllStudents();
        studentCombo.removeAllItems();
        if (students != null) {
            for (Student s : students) {
                if (s != null) {
                    studentCombo.addItem(s.getStudentId() + " - " + s.getFullName());
                }
            }
        }

        // Load subjects
        List<Subject> subjects = subjectService.retrieveAllSubjects();
        subjectCombo.removeAllItems();
        if (subjects != null) {
            for (Subject s : subjects) {
                if (s != null) {
                    subjectCombo.addItem(s.getSubjectId() + " - " + s.getSubjectName());
                }
            }
        }

    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Failed to load students or subjects: " + e.getMessage());
    }
}


// LOAD TABLE
private void loadTable() {
    try {
        List<PerformanceDTO> list = performanceService.retrieveAllPerformances();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear previous rows

        if (list != null) {
            for (PerformanceDTO p : list) {
                if (p == null) continue;

                Student student = studentService.findStudentById(p.getStudentId());
                Subject subject = subjectService.searchSubjectById(p.getSubjectId());

                String studentName = (student != null) ? student.getFullName() : "Unknown";
                String subjectName = (subject != null) ? subject.getSubjectName() : "Unknown";

                model.addRow(new Object[]{
                    p.getPerformanceId(),
                    studentName,
                    subjectName,
                    p.getScore(),
                    p.getGrade()
                });
            }
        }

    } catch (RemoteException e) {
        JOptionPane.showMessageDialog(this, "Failed to load performance table: " + e.getMessage());
    }
}



@Override
public void setVisible(boolean aFlag) {
    super.setVisible(aFlag);
    if (aFlag) {
        loadStudentAndSubject();
        loadTable();
    }
}

    private void exportTableToCSV(JTable table) {
    JFileChooser chooser = new JFileChooser();
    chooser.setSelectedFile(new File("performance_report.csv"));

    if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try (FileWriter fw = new FileWriter(file)) {

            // Write column headers
            for (int i = 0; i < table.getColumnCount(); i++) {
                fw.write(table.getColumnName(i) + ",");
            }
            fw.write("\n");

            // Write table rows
            for (int i = 0; i < table.getRowCount(); i++) {
                for (int j = 0; j < table.getColumnCount(); j++) {
                    Object value = table.getValueAt(i, j);
                    fw.write((value != null ? value.toString() : "") + ",");
                }
                fw.write("\n");
            }

            JOptionPane.showMessageDialog(this,
                    "Performance report exported successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Failed to export report: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton csvBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton excelBtn;
    private javax.swing.JTextField gradeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pdfBtn;
    private javax.swing.JTextField performanceIdTxt;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton registerBtn;
    private javax.swing.JTextField scoreTxt;
    private javax.swing.JButton searchBtn4;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JComboBox<String> studentCombo;
    private javax.swing.JComboBox<String> subjectCombo;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
