/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ApartmentDao;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.Apartment;
import java.util.regex.Pattern;

/**
 *
 * @author User-104
 */
public class ApartmentPanel extends javax.swing.JPanel {

    private int selectedId = -1;

    /**
     * Creates new form ApartmentPanel
     */
    public ApartmentPanel() {
        initComponents();
        
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        jTable1MouseClicked(evt);
    }
});
        
        rentTypeCombo.removeAllItems();
        rentTypeCombo.addItem("Daily");
        rentTypeCombo.addItem("Weekly");
        rentTypeCombo.addItem("Monthly");
        rentTypeCombo.addItem("Yearly");

        //table
        JTableHeader header = jTable1.getTableHeader();
header.setFont(new Font("Segoe UI", Font.BOLD, 16));

header.setDefaultRenderer((table, value, isSelected, hasFocus, row, column) -> {
    JLabel lbl = new JLabel(value.toString());
    lbl.setOpaque(true);
    lbl.setBackground(new Color(0, 102, 102));   // Your background color
    lbl.setForeground(Color.WHITE);               // Text color
    //lbl.setHorizontalAlignment(JLabel.CENTER);    // Center text
    lbl.setFont(new Font("Segoe UI", Font.BOLD, 18));
    return lbl;
});
//table
// load table initially
        loadApartmentTable();
    }

// ---------- VALIDATION HELPERS ----------
    private boolean isValidApartmentNumberInput(String input) {
        // Accept digits or digits with prefix; we will auto-add N- if user forgot
        // valid pattern after prefix: N- followed by 1+ digits or letters if you allow letters
        if (input == null || input.trim().isEmpty()) return false;
        // allow numbers only in input field (user types digits), or full "N-123"
        String trimmed = input.trim();
        if (trimmed.startsWith("N-")) trimmed = trimmed.substring(2);
        // ensure remaining has at least one digit and contains only letters/digits/hyphen underscore? We'll require digits.
        return Pattern.matches("\\d{1,}", trimmed);
    }

    private String normalizeApartmentNumber(String userInput) {
        String t = userInput.trim();
        if (!t.startsWith("N-")) {
            t = "N-" + t;
        }
        return t;
    }

    private boolean isValidRentAmount(String rentText) {
        if (rentText == null || rentText.trim().isEmpty()) return false;
        try {
            double r = Double.parseDouble(rentText.trim());
            return r > 0; // rent must be positive
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    private boolean isValidLocation(String loc) {
        return loc != null && !loc.trim().isEmpty() && loc.trim().length() >= 2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        registrationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        apartmentNumberTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        locationTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rentAmountTxt = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        occupiedCombo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rentTypeCombo = new javax.swing.JComboBox<>();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/side3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apartment Page");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel8)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        registrationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Apartments Registration");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Apartment number");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Location");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Rent Amount");

        addBtn.setBackground(new java.awt.Color(0, 51, 51));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        updateBtn.setText("update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        deleteBtn.setText("delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        refreshBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        refreshBtn.setText("refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setText("Occupied");

        occupiedCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Occupied" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setText("Rent Type");

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(addBtn)
                        .addGap(39, 39, 39)
                        .addComponent(updateBtn)))
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registrationPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(deleteBtn)
                        .addGap(46, 46, 46)
                        .addComponent(refreshBtn)
                        .addGap(30, 30, 30))
                    .addGroup(registrationPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rentTypeCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(registrationPanelLayout.createSequentialGroup()
                                .addComponent(apartmentNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(occupiedCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rentAmountTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(locationTxt))))
                .addGap(52, 52, 52))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apartmentNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(43, 43, 43)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(43, 43, 43)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(48, 48, 48)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(occupiedCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteBtn)
                    .addComponent(addBtn)
                    .addComponent(refreshBtn)
                    .addComponent(updateBtn))
                .addGap(25, 25, 25))
        );

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));
        tablePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "Apartment NO", "Location", "Rent amount", "Occupied", "Rent Type"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        searchBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        searchBtn.setText("search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tablePanelLayout.createSequentialGroup()
                        .addComponent(searchTxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
    String numberInput = apartmentNumberTxt.getText().trim();
        String location = locationTxt.getText().trim();
        String rentText = rentAmountTxt.getText().trim();
        String rentType = (String) rentTypeCombo.getSelectedItem();
        String occupiedText = (String) occupiedCombo.getSelectedItem();

        // Business & technical validations (View-level)
        if (numberInput.isEmpty() || location.isEmpty() || rentText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all required fields!", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isValidApartmentNumberInput(numberInput)) {
            JOptionPane.showMessageDialog(this, "Apartment number must be digits (we will prefix with N-). Example: 101", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isValidLocation(location)) {
            JOptionPane.showMessageDialog(this, "Location is too short or invalid.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!isValidRentAmount(rentText)) {
            JOptionPane.showMessageDialog(this, "Rent amount must be a positive number.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        double rentAmount;
        try {
            rentAmount = Double.parseDouble(rentText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Rent amount must be numeric.", "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Normalize apartment number to N- prefix
        String normalizedNumber = normalizeApartmentNumber(numberInput);

        // Prepare model
        Apartment apt = new Apartment();
        apt.setApartmentNumber(normalizedNumber);
        apt.setLocation(location);
        apt.setRentAmount(rentAmount);
        apt.setOccupied("Occupied".equalsIgnoreCase(occupiedText));
        apt.setRent_type(rentType);

        // DAO-level technical validations (unique)
        ApartmentDao dao = new ApartmentDao();
        if (dao.existsApartmentNumber(normalizedNumber)) {
            JOptionPane.showMessageDialog(this, "Apartment number already exists: " + normalizedNumber, "Validation", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (dao.addApartment(apt)) {
            JOptionPane.showMessageDialog(this, "Apartment added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadApartmentTable();
            clearFields();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add apartment. See console for details.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
                                          
    if (selectedId == -1) {
        JOptionPane.showMessageDialog(this, "Select an apartment from the table first!", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    String numberInput = apartmentNumberTxt.getText().trim();
    String location = locationTxt.getText().trim();
    String rentText = rentAmountTxt.getText().trim();
    String rentType = (String) rentTypeCombo.getSelectedItem();
    String occupiedText = (String) occupiedCombo.getSelectedItem();

    if (numberInput.isEmpty() || location.isEmpty() || rentText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all required fields!", "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!isValidApartmentNumberInput(numberInput)) {
        JOptionPane.showMessageDialog(this, "Invalid apartment number. Example: 101 (we store as N-101).", "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!isValidRentAmount(rentText)) {
        JOptionPane.showMessageDialog(this, "Rent amount must be a positive number.", "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double rentAmount;
    try {
        rentAmount = Double.parseDouble(rentText);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Rent amount must be numeric.", "Validation", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Normalize apartment number
    String normalizedNumber = normalizeApartmentNumber(numberInput);

    ApartmentDao dao = new ApartmentDao();
    Apartment dbApartment = dao.getApartmentById(selectedId);
    if (dbApartment == null) {
        JOptionPane.showMessageDialog(this, "Apartment not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // BUSINESS RULE: Cannot change occupied to available manually
    boolean newOccupied = "Occupied".equalsIgnoreCase(occupiedText);
    if (dbApartment.isOccupied() && !newOccupied) {
        JOptionPane.showMessageDialog(this, "Occupied apartment cannot be marked as available manually!", "Validation", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // BUSINESS RULE: Location should not change
    if (!dbApartment.getLocation().equals(location)) {
        JOptionPane.showMessageDialog(this, "Location cannot be changed!", "Validation", JOptionPane.WARNING_MESSAGE);
        location = dbApartment.getLocation(); // revert to original
    }

    // Confirm sensitive change: apartment number
    if (!dbApartment.getApartmentNumber().equals(normalizedNumber)) {
        int choice = JOptionPane.showConfirmDialog(
            this,
            "You are changing the apartment number. Are you sure?",
            "Confirm Change",
            JOptionPane.YES_NO_OPTION
        );
        if (choice != JOptionPane.YES_OPTION) return;
    }

    Apartment apt = new Apartment();
    apt.setId(selectedId);
    apt.setApartmentNumber(normalizedNumber);
    apt.setLocation(location);
    apt.setRentAmount(rentAmount);
    apt.setOccupied(newOccupied);
    apt.setRent_type(rentType);

    if (dao.updateApartment(apt)) {
        JOptionPane.showMessageDialog(this, "Apartment updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        loadApartmentTable();
        clearFields();
        selectedId = -1;
    } else {
        JOptionPane.showMessageDialog(this, "Failed to update apartment. Check console for details.", "Error", JOptionPane.ERROR_MESSAGE);
    }
       
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed

        if (selectedId == -1) {
            JOptionPane.showMessageDialog(this, "Please select an apartment to delete!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ApartmentDao dao = new ApartmentDao();
        Apartment a = dao.getApartmentById(selectedId);
        if (a == null) {
            JOptionPane.showMessageDialog(this, "Selected apartment not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (a.isOccupied()) {
            JOptionPane.showMessageDialog(this, "Cannot delete an occupied apartment. Set it to Available first.", "Validation", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this apartment (" + a.getApartmentNumber() + ")?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {
            if (dao.deleteApartment(selectedId)) {
                JOptionPane.showMessageDialog(this, "Apartment deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadApartmentTable();
                clearFields();
                selectedId = -1;
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete apartment. See console for details.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        clearFields();
        loadApartmentTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed

       String keyword = searchTxt.getText().trim();
        ApartmentDao dao = new ApartmentDao();
        List<Apartment> apartmentList = dao.searchApartments(keyword);

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Apartment a : apartmentList) {
            model.addRow(new Object[]{
                a.getId(),
                a.getApartmentNumber(),
                a.getLocation(),
                a.getRentAmount(),
                a.isOccupied() ? "Occupied" : "Available",
                a.getRent_type()
            });
        }
    }//GEN-LAST:event_searchBtnActionPerformed

  public void loadApartmentTable() {
        ApartmentDao dao = new ApartmentDao();
        List<Apartment> list = dao.getAllApartments();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        for (Apartment a : list) {
            model.addRow(new Object[]{
                a.getId(),
                a.getApartmentNumber(),
                a.getLocation(),
                a.getRentAmount(),
                a.isOccupied() ? "Occupied" : "Available",
                a.getRent_type()
            });
        }
    }

  //clear fields
private void clearFields() {
    apartmentNumberTxt.setText("");
    locationTxt.setText("");
    rentAmountTxt.setText("");
    occupiedCombo.setSelectedIndex(0);
    rentTypeCombo.setSelectedIndex(0); // reset rent type too
    searchTxt.setText("");
    selectedId = -1;
}


 private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        int row = jTable1.getSelectedRow();
        if (row < 0) return;

        selectedId = Integer.parseInt(jTable1.getValueAt(row, 0).toString());

        apartmentNumberTxt.setText(jTable1.getValueAt(row, 1).toString().replaceFirst("^N-", "")); // show without prefix for easy editing
        locationTxt.setText(jTable1.getValueAt(row, 2).toString());
        rentAmountTxt.setText(jTable1.getValueAt(row, 3).toString());
        occupiedCombo.setSelectedItem(jTable1.getValueAt(row, 4).toString());
        // FIXED: set rent type too
        rentTypeCombo.setSelectedItem(jTable1.getValueAt(row, 5).toString());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField apartmentNumberTxt;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField locationTxt;
    private javax.swing.JComboBox<String> occupiedCombo;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JTextField rentAmountTxt;
    private javax.swing.JComboBox<String> rentTypeCombo;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
