/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author User-104
 */
public class DashBoard extends javax.swing.JFrame {

    private HomePage homePage;
    private ApartmentPanel apartmentPanel;
    private TenantPanel tenantPanel;
    private TenantTrackingPanel tenantTrackingPanel;
    private PaymentPanel paymentPanel;
    private MaintenancePanel maintenancePanel;
    private ExpensePanel expensePanel;
    private ProfitLossPanel profitLossPanel;
    private NotificationPanel notificationPanel;
    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        initCards();
       // setActiveMenuButton(homeBtn);
    }
    
    private void initCards() {
    homePage = new HomePage();
    apartmentPanel = new ApartmentPanel();
    tenantPanel= new TenantPanel();
    tenantTrackingPanel = new  TenantTrackingPanel();
    paymentPanel = new PaymentPanel();
    maintenancePanel = new MaintenancePanel();
    expensePanel = new ExpensePanel();
    profitLossPanel = new ProfitLossPanel();
     notificationPanel = new NotificationPanel();

    //add
    contentPanel.add(homePage,"home");
    contentPanel.add(apartmentPanel,"apartment");
    contentPanel.add(tenantPanel,"tenant");
    contentPanel.add(tenantTrackingPanel,"tenant_tracking");
    contentPanel.add(paymentPanel,"payment");
    contentPanel.add(profitLossPanel,"profitLoss");
    contentPanel.add(maintenancePanel,"maintenance");
    contentPanel.add(expensePanel,"expense");
    contentPanel.add(notificationPanel,"notification");
    java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"home");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        leftPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        navigationPanel = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        apartmentsBtn = new javax.swing.JButton();
        tenantsBtn = new javax.swing.JButton();
        paymentsBtn = new javax.swing.JButton();
        maintenanceBtn = new javax.swing.JButton();
        expenseBtn = new javax.swing.JButton();
        tenantTrackingBtn = new javax.swing.JButton();
        notificationBtn = new javax.swing.JButton();
        profitLossBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        headerPanel.setPreferredSize(new java.awt.Dimension(711, 150));
        headerPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(0, 51, 51));
        topPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apartments Rent Management System");

        logoutBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(0, 102, 102));
        logoutBtn.setText("Logout");
        logoutBtn.setHideActionText(true);
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1438, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        headerPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        leftPanel.setBackground(new java.awt.Color(0, 102, 102));
        leftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        leftPanel.setPreferredSize(new java.awt.Dimension(300, 96));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Navigate through the System ");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        headerPanel.add(leftPanel, java.awt.BorderLayout.LINE_START);

        navigationPanel.setBackground(new java.awt.Color(0, 204, 204));
        navigationPanel.setLayout(new java.awt.GridLayout(1, 0));

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(homeBtn);

        apartmentsBtn.setText("Manage Apartments");
        apartmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentsBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(apartmentsBtn);

        tenantsBtn.setText("Manage Tenants");
        tenantsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantsBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(tenantsBtn);

        paymentsBtn.setText("Manage Payments");
        paymentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(paymentsBtn);

        maintenanceBtn.setText("Manage Maintenance");
        maintenanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintenanceBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(maintenanceBtn);

        expenseBtn.setText("Manage Expense");
        expenseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expenseBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(expenseBtn);

        tenantTrackingBtn.setText("Tenant Tracking");
        tenantTrackingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantTrackingBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(tenantTrackingBtn);

        notificationBtn.setText("Notification");
        notificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificationBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(notificationBtn);

        profitLossBtn.setText("Profit Loss Overview");
        profitLossBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profitLossBtnActionPerformed(evt);
            }
        });
        navigationPanel.add(profitLossBtn);

        headerPanel.add(navigationPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
    java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"home");
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
                                          

    int choice = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
    );

    if (choice == JOptionPane.YES_OPTION) {

        // Close the current window
        this.dispose();

        // Open login form
        LoginForm login = new LoginForm();
        login.setVisible(true);
    }

    }//GEN-LAST:event_logoutBtnActionPerformed

    private void tenantsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantsBtnActionPerformed
       java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"tenant");
    }//GEN-LAST:event_tenantsBtnActionPerformed

    private void apartmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentsBtnActionPerformed
    java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"apartment");
    }//GEN-LAST:event_apartmentsBtnActionPerformed

    private void paymentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsBtnActionPerformed
     java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"payment");
    }//GEN-LAST:event_paymentsBtnActionPerformed

    private void tenantTrackingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantTrackingBtnActionPerformed
          java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"tenant_tracking");
    }//GEN-LAST:event_tenantTrackingBtnActionPerformed

    private void maintenanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintenanceBtnActionPerformed
             java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"maintenance");
    }//GEN-LAST:event_maintenanceBtnActionPerformed

    private void expenseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expenseBtnActionPerformed
              java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"expense");
    }//GEN-LAST:event_expenseBtnActionPerformed

    private void profitLossBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profitLossBtnActionPerformed
        java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"profitLoss");
    }//GEN-LAST:event_profitLossBtnActionPerformed

    private void notificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificationBtnActionPerformed
         java.awt.CardLayout cl =(java.awt.CardLayout) contentPanel.getLayout();
    cl.show(contentPanel,"notification");
    }//GEN-LAST:event_notificationBtnActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apartmentsBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton expenseBtn;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton maintenanceBtn;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton notificationBtn;
    private javax.swing.JButton paymentsBtn;
    private javax.swing.JButton profitLossBtn;
    private javax.swing.JButton tenantTrackingBtn;
    private javax.swing.JButton tenantsBtn;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
